columnSuffix: null
handle: hockeyHoursOpen
instructions: null
name: 'Hockey Hours Open'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
