columnSuffix: null
handle: hockeyHoursClose
instructions: null
name: 'Hockey Hours Close'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
