columnSuffix: null
handle: isIndoor
instructions: null
name: 'Is Indoor'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
